### PR TITLE
Fixes & Additions

### PR DESCRIPTION
**Pull request by dragonwocky**
I just fixed a couple of faults in the code, and fixed/updated your plugin.yml and Main.php. I also added the config (rules.yml) and if you wish I can also do some work on Rules.php, fixing stuff from that up and adding configurable rules etc (Note: Also tweeted you about this :P)

### CODE REVIEW

**Comment by CaptainDuck** [comment]
Wow, nice! Thanks so much for your help, But how can I make the Rules.yml edit the rule messages? Thanks so much for this, I'll add you on the special thanks to list :D

**Comment by dragonwocky** [comment]
You can easily make rules.yml edit the rules messages with a simple function, if you like I can make another pull request that adds that functionality in to all the messages so then you can look at this code and know how to do it again yourself later

**Comment by CaptainDuck** [comment]
Okay, sure pls do another Pull Request, the Crash has been fix but there is a another one, a Crash based on the BaseClassLoader, maybe its from the API?? Maybe u can aso fix it? And I'm sorry if I'm asking a lot I'm a newbie :D

**Comment by dragonwocky** [comment]
I'll look into it, could you provide any specific errors? Or maybe your crash dump?

**Comment by CaptainDuck** [comment]
Okay, here's a crash dump:

Error: Class AdvancedRules\Main not found
File: /src/spl/BaseClassLoader
Line: 131
Type: notice

THIS CRASH WAS CAUSED BY A PLUGIN
此次出错由插件引起

Code:
[122]      *
[123]      \* @return bool
[124]      */
[125]     public function loadClass($name){
[126]         $path = $this->findClass($name);
[127]         if($path !== null){
[128]             include($path);
[129]             if(!class_exists($name, false) and !interface_exists($name, false) and !trait_exists($name, false)){
[130]               if($this->getParent() === null){
[131]                   throw new ClassNotFoundException("Class $name not found");
[132]               }
[133]                 return false;
[134]             }
[135] 
[136]           if(method_exists($name, "onClassLoaded") and (new ReflectionClass($name))->getMethod("onClassLoaded")->isStatic()){
[137]               $name::onClassLoaded();
[138]           }
[139]  
[140]           $this->classes[] = $name;
[141] 

Backtrace:
#0 (): spl_autoload_call(string AdvancedRules\Main)
#1 /src/pocketmine/plugin/PharPluginLoader(64): class_exists(string AdvancedRules\Main, boolean 1)
#2 /src/pocketmine/plugin/PluginManager(155): pocketmine\plugin\PharPluginLoader->loadPlugin(string phar:///home/JM2/42495096/plugins/phar_AdvancedRules-master_hgzCwiiEoaH8uYx.phar)
#3 /src/pocketmine/plugin/PluginManager(333): pocketmine\plugin\PluginManager->loadPlugin(string /home/JM2/42495096/plugins/phar_AdvancedRules-master_hgzCwiiEoaH8uYx.phar, array Array())
#4 /src/pocketmine/Server(1962): pocketmine\plugin\PluginManager->loadPlugins(string /home/JM2/42495096/plugins/)
#5 /src/pocketmine/PocketMine(467): pocketmine\Server->__construct(pocketmine\CompatibleClassLoader object, pocketmine\utils\MainLogger object, string phar:///home/JM2/42495096/PocketMine-MP.phar/, string /home/JM2/42495096/, string /home/JM2/42495096/plugins/, string unknown)
#6 (1): require_once(string phar:///home/JM2/42495096/PocketMine-MP.phar/src/pocketmine/PocketMine.php)

uname -a: Linux uk-pe-1.node.nitrous.it 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt20-1+deb8u3 (2016-01-17) x86_64
PHP version: 7.0.3
Zend version: 3.0.0
OS : Linux, linux

Loaded plugins:
加载的插件:
BuyCraft 1.2.2 by Falkirks for API(s) 1.0.0
DevTools 1.11.0 by PocketMine Team for API(s) 2.0.0

**Comment by dragonwocky** [comment]
Ok, either way this plugin still needs a lot of changes to Main.php and Rules.php, gtg sleep soon, but I will try to do tomorrow

**Comment by CaptainDuck** [comment]
Okay, sleep well! :D

**Pull request merged**
